import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Header from "@/sections/Header";
import AuthProvider from "@/components/AuthProvider";
import UserCreationHandler from "@/components/UserCreationHandler";
import Footer from "@/sections/Footer";
import { Toaster } from "@/components/ui/sonner"


const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage",
  weight: ['400', '500', '600', '700', '800'],
  subsets: ["latin"],
})




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${bricolageGrotesque.className} antialiased  mx-auto bg-[#DAF6ED] px-2 sm:px-4 md:p-0 max-w-[936px]`}

      >
        <AuthProvider>
        <UserCreationHandler />
        <Header className=""/>
        {children}
        <Footer />
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
