export {default as LadyWithLaptop} from './ladywithLaptop.svg'
export {default as ChatBox} from './ChatBox.svg'
export {default as AppleLogo } from './AppleLogo.svg'
export {default as ThreeDots } from './DotsThreeOutlineVertical.svg'
export {default as PodCast} from './PodCast.svg'
export {default as StarFour} from './StarFour.svg'
export {default as RocketLaunch} from './RocketLaunch.svg'
export {default as PatreonBackground} from './PatreonLogo.svg'
export {default as Avocado} from './Avocado.svg'
export {default as Group4} from './Group4.svg'
export {default as XCircle} from './XCircle.svg'
export {default as CheckCircle} from './CheckCircle.svg'